# Generated by Django 4.1.6 on 2023-02-04 14:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Raspberry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(unique=True)),
                ('admin_code', models.IntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(900000000)])),
                ('user_code', models.IntegerField(validators=[django.core.validators.MinValueValidator(100000), django.core.validators.MaxValueValidator(900000000)])),
                ('admins', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ThiefRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
                ('raspberry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_system.raspberry')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SmokeRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('gas_type', models.CharField(max_length=250)),
                ('value', models.FloatField()),
                ('raspberry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security_system.raspberry')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
